'use client';

import { useEffect } from 'react';
import { toast } from 'sonner';
import { useTranslations } from 'next-intl';

// Long-lived tabs (KDS/POS tablets) never navigate, so the browser rarely
// re-checks the service worker on its own: poll on an interval + on focus.
const UPDATE_CHECK_INTERVAL_MS = 15 * 60 * 1000;
const TOAST_ID = 'sw-update-prompt';

/**
 * Detects a waiting (freshly deployed) PWA service worker and shows a
 * persistent "new version available" toast. On click, tells the waiting
 * worker to take over (SKIP_WAITING, handled natively by the Workbox SW
 * generated by @ducanh2912/next-pwa) and reloads once it controls the page.
 *
 * next.config.mjs registers the SW with skipWaiting:false, so without this
 * component users keep the old version until every tab is closed.
 */
export function ServiceWorkerUpdatePrompt() {
  const t = useTranslations('common.appUpdate');

  useEffect(() => {
    if (!('serviceWorker' in navigator)) return;

    let cancelled = false;
    let intervalId: number | undefined;
    let registration: ServiceWorkerRegistration | undefined;

    const reloadOnControllerChange = () => {
      window.location.reload();
    };

    const promptUpdate = (waiting: ServiceWorker) => {
      toast(t('title'), {
        id: TOAST_ID,
        description: t('description'),
        duration: Infinity,
        action: {
          label: t('action'),
          onClick: () => {
            navigator.serviceWorker.addEventListener('controllerchange', reloadOnControllerChange, {
              once: true,
            });
            waiting.postMessage({ type: 'SKIP_WAITING' });
          },
        },
      });
    };

    const onUpdateFound = () => {
      const installing = registration?.installing;
      if (!installing) return;
      installing.addEventListener('statechange', () => {
        // "installed" with an existing controller = an update is waiting
        // (without a controller it is the very first install, nothing to prompt).
        if (
          installing.state === 'installed' &&
          navigator.serviceWorker.controller &&
          registration?.waiting
        ) {
          promptUpdate(registration.waiting);
        }
      });
    };

    // Benign by design: update() fails while offline; the next tick retries.
    const checkForUpdate = () => {
      registration?.update().catch(() => undefined);
    };

    const onVisibilityChange = () => {
      if (document.visibilityState === 'visible') checkForUpdate();
    };

    navigator.serviceWorker.getRegistration().then((reg) => {
      if (cancelled || !reg) return;
      registration = reg;
      // A new version may already be waiting from a previous visit.
      if (reg.waiting && navigator.serviceWorker.controller) {
        promptUpdate(reg.waiting);
      }
      reg.addEventListener('updatefound', onUpdateFound);
      intervalId = window.setInterval(checkForUpdate, UPDATE_CHECK_INTERVAL_MS);
    });

    document.addEventListener('visibilitychange', onVisibilityChange);

    return () => {
      cancelled = true;
      if (intervalId !== undefined) window.clearInterval(intervalId);
      document.removeEventListener('visibilitychange', onVisibilityChange);
      registration?.removeEventListener('updatefound', onUpdateFound);
      navigator.serviceWorker.removeEventListener('controllerchange', reloadOnControllerChange);
    };
  }, [t]);

  return null;
}
