// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --local > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          created_at: string
          slug: string
          name: string
          logo_url: string | null
          primary_color: string | null
          secondary_color: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          slug: string
          name: string
          logo_url?: string | null
          primary_color?: string | null
          secondary_color?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          slug?: string
          name?: string
          logo_url?: string | null
          primary_color?: string | null
          secondary_color?: string | null
        }
      }
      // Add more tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
