/**
 * Maps category names to PNG icon filenames in /public/category-icons/.
 * Matching is:
 * 1. Exact lowercase+normalized lookup
 * 2. Substring match in either direction (fall-through)
 * 3. Neutral "specialty" fallback for unknown categories.
 *
 * Keep keys lowercase, ASCII-normalized (no accents) for predictable lookups.
 */
export const CATEGORY_ICONS: Record<string, string> = {
  burger: 'burger.png',
  burgers: 'burger.png',
  hamburger: 'burger.png',
  hamburgers: 'burger.png',
  entree: 'caribbean.png',
  entrees: 'caribbean.png',
  starters: 'caribbean.png',
  'pour commencer': 'caribbean.png',
  plats: 'caribbean.png',
  'plat principal': 'caribbean.png',
  'plats principaux': 'caribbean.png',
  'main course': 'caribbean.png',
  grillade: 'caribbean.png',
  grills: 'caribbean.png',
  grille: 'caribbean.png',
  bbq: 'caribbean.png',
  asiatique: 'asian.png',
  asian: 'asian.png',
  noodles: 'asian.png',
  soupe: 'asian.png',
  soup: 'asian.png',
  soupes: 'asian.png',
  pates: 'asian.png',
  pasta: 'asian.png',
  pastas: 'asian.png',
  lasagna: 'asian.png',
  indien: 'indian.png',
  indian: 'indian.png',
  curry: 'indian.png',
  africain: 'indian.png',
  african: 'indian.png',
  'plats africains': 'indian.png',
  glace: 'ice-cream.png',
  glaces: 'ice-cream.png',
  'ice cream': 'ice-cream.png',
  americain: 'american.png',
  american: 'american.png',
  'hot dog': 'american.png',
  alcool: 'alcohol.png',
  alcohol: 'alcohol.png',
  vin: 'alcohol.png',
  vins: 'alcohol.png',
  wine: 'alcohol.png',
  biere: 'alcohol.png',
  bieres: 'alcohol.png',
  beer: 'alcohol.png',
  cocktail: 'alcohol.png',
  cocktails: 'alcohol.png',
  'cocktails alcoolises': 'alcohol.png',
  'cocktails sans alcool': 'alcohol.png',
  aperitif: 'alcohol.png',
  aperitifs: 'alcohol.png',
  boisson: 'alcohol.png',
  boissons: 'alcohol.png',
  drinks: 'alcohol.png',
  beverages: 'alcohol.png',
  chinois: 'chinese.png',
  chinese: 'chinese.png',
  'dim sum': 'chinese.png',
  francais: 'french.png',
  french: 'french.png',
  viande: 'french.png',
  steak: 'french.png',
  halal: 'halal.png',
  brochette: 'halal.png',
  kebab: 'halal.png',
  poulet: 'halal.png',
  chicken: 'halal.png',
  dessert: 'dessert.png',
  desserts: 'dessert.png',
  douceurs: 'dessert.png',
  patisserie: 'dessert.png',
  gateau: 'dessert.png',
  tart: 'dessert.png',
  'fast food': 'fast-food.png',
  'fast-food': 'fast-food.png',
  rapide: 'fast-food.png',
  frites: 'fast-food.png',
  specialite: 'specialty.png',
  specialty: 'specialty.png',
  epicerie: 'specialty.png',
  cafe: 'specialty.png',
  coffee: 'specialty.png',
  the: 'specialty.png',
  tea: 'specialty.png',
  'boissons chaudes': 'specialty.png',
  snack: 'convenience.png',
  snacks: 'convenience.png',
  convenience: 'convenience.png',
  sandwich: 'convenience.png',
  sandwiches: 'convenience.png',
  courses: 'grocery.png',
  grocery: 'grocery.png',
  emporter: 'takeout.png',
  'a emporter': 'takeout.png',
  takeout: 'takeout.png',
  takeaway: 'takeout.png',
  fleurs: 'flowers.png',
  flowers: 'flowers.png',
  salade: 'specialty.png',
  salades: 'specialty.png',
  salad: 'specialty.png',
  salads: 'specialty.png',
  seafood: 'french.png',
  'fruits de mer': 'french.png',
  poisson: 'french.png',
  fish: 'french.png',
  vegetarian: 'grocery.png',
  vegetarien: 'grocery.png',
  vegan: 'grocery.png',
};

export function getCategoryIcon(name: string): string {
  const lower = name
    .toLowerCase()
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
  if (CATEGORY_ICONS[lower]) return `/category-icons/${CATEGORY_ICONS[lower]}`;
  for (const [key, file] of Object.entries(CATEGORY_ICONS)) {
    if (lower.includes(key) || key.includes(lower)) return `/category-icons/${file}`;
  }
  return '/category-icons/specialty.png';
}
